### ISSUE TITLE
Reduced Density Matrices

### ISSUE THREAD

**Issue by chrisnakers** [google/TensorNetwork#144]
Consider a tensor network that defines a state on some dangling legs. I would like to be able to select a subset of those legs and output the reduced density matrix of those legs.

**Comment by amilsted** [comment]
Thanks for trying out TensorNetwork! As you may have noticed, we don't currently build any semantics into TensorNetwork itself - we make no assumptions in the core code about the meaning of the tensor that the network represents. This is a clean way to implement basic tensor network features.

That said, it would be interesting to explore how best to add such quantum functionality! One way would be to create a "wavefunction" or "quantum_state" class that inherits from our `Network` class. This could then provide features like the ones you suggest on top of what we have already. Alternatively, this could also be done via a library of functions that take tensor networks as inputs, returning e.g. a new network representing the reduced state.

Any thoughts @Thenerdstation and @mganahl ?

**Comment by Thenerdstation** [comment]
I agree with Ash, this seems like something for for an extension of `TensorNetwork`.

Though I also wonder if it's even really needed. Doing it with the current features of the library should be fairly straightforward.

For example:

```python
net1, qubit_edges1 = make_wavefunction(...)
net2, qubit_edges2 = make_wavefunction(...)
net1.add_subnetwork(net2)
for qubit in [3, 5, 7]: # or whatever you want.
  net.connect(qubit_edges1[qubit], qubit_edges2[qubit])

tensornetwork.contractors.naive(net1)

net1.get_final_node().tensor # Here is your RDM.
```

Pretty short and sweet. The only other reason I could see for adding this is to optimize the compute needed to calculate the RDM. This would relate back to our "inner shape vs outer shape" issue from earlier.

**Comment by amilsted** [comment]
Yes, this stuff is not hard to do (you're quite the quantum physicist these days, @Thenerdstation!). However, including it either in TensorNetwork, or in a package that extends it, would surely be useful for some people. This could form a new "example", or be an extension of the "wavefunctions" example we currently have, or it could become a core part of TensorNetwork.

My inclination would be *not* to add it to the core since I think it is better to focus on the basics in TensorNetwork. As such I think, insofar as this goes beyond an "example" or "experiment", it would be better off as a separate, dependent project. How about "QuantumTensorNetwork"? ;)

**Comment by Thenerdstation** [comment]
Thanks! I've been taking classes ^-^.

**Comment by amilsted** [comment]
Related question: What is our long-term plan for the "experiments"? Do they eventually get upgraded to fully-fledged parts of the library, or split out into their own separate projects?

**Comment by chrisnakers** [comment]
Thanks! If you do make a QuantumTensorNetwork dependent project, I would use it!

**Comment by Thenerdstation** [comment]
I think we'll keep it under this TensorNetwork package.
