### ISSUE TITLE
Adding tf tensors with numpy backend set creates nodes with zero edges

### ISSUE THREAD

**Issue by sidek** [google/TensorNetwork#166]
If I:
1. Set numpy backend
2. Try to add a node with underlying tensor a tensorflow tensor to my network

TensorNetwork won't initially complain, and the added node will have correct underlying (tensorflow-typed) tensor. However, the node created will have no edges. 

It would be better if tensornetwork threw an error/warning when I tried to add a tensorflow tensor as a node to the numpy-backed network.

Example code which causes this weird behaviour follows.

Specifically, say I create a numpy-backended tensornetwork with a tensorflow node:
```
import tensorflow as tf 
import tensornetwork
tensornetwork.set_default_backend("numpy")
t = tf.random.uniform((2,2,2,2))
net = tensornetwork.TensorNetwork()
tN = net.add_node(t)
```
The node has the correct underlying tensor: 
```
>>tN.tensor
array(<tf.Tensor 'random_uniform_1:0' shape=(2, 2, 2, 2) dtype=float32>,
      dtype=object)
```
but it doesn't have any edges:
``` 
>>tN.edges
[]
```
Of course,  all the code works properly if I remove the line `tensornetwork.set_default_backend("numpy")`
; in that case, 
```
>>tN.edges
[<tensornetwork.network_components.Edge at 0xb2de19f28>,
 <tensornetwork.network_components.Edge at 0xb2de19f60>,
 <tensornetwork.network_components.Edge at 0xb2de19f98>,
 <tensornetwork.network_components.Edge at 0xb2de19fd0>]

```

This behaviour is not commutative. Namely, if I try to add a numpy ndarray to a tensorflow-backed tensornetwork, it's silently cast to a tensorflow tensor, and everything works as expected. 

Because silent casting tf -> np is much worse than np -> tf, non-commutativity here seems inevitable, but warning about it would be nice.

**Comment by MichaelMarien** [comment]
Indeed, the reason is that the when using the numpy backend, the Tensorflow tensor gets cast using np.asarray before the Node is constructed. However, as you pointed out this casting is not very nice. It seems tricky to fix it and a warning does not seem strong enough as I image this can cause serious and hard to debug problems downstream. I'm thinking it might be best to throw ValueErrors when we cannot reliably cast to chosen backend.

**Comment by Thenerdstation** [comment]
Yeah that's tough, especially because I think we should allow users to create nodes just from list definitions.

The way I currently see it, have 2 options.

1. Only accept `np.array`s for the numpy backend. Could be moderately annoying for the end user to explicitly put `np.array` everywhere, but it fully fixes the problem.

2. Disallow specific types like `tf.Tensor`, less restrictive but more likely to still cause silent errors.

I'm leaning towards 1.

**Comment by MichaelMarien** [comment]
Can we not have a slightly better version of 1. If we allow a few white-listed types in the backend's convert_to_tensor method, we also solve this? For np we can allow array, lists and Torch tensors?

**Comment by Thenerdstation** [comment]
I'm not sure I agree with allowing Torch tensors for the numpy backend. Do you have a reason for wanting to support this?

**Comment by MichaelMarien** [comment]
Don't really have a use case. For me, most important is failing fast and clearly to the user. So I can live with a clear ValueError and message "please provide Numpy array, other types not allowed" as long as it appears immediately.

**Comment by Thenerdstation** [comment]
In that case let's just stick fully with option 1. Like you said failing fast and loud is better than failing silently.
