### ISSUE TITLE
Conjugation operation for nodes

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#195]
Many tensor networks used in practice are invariant under complex conjugation. An example is the energy expectation value of an MPS, which is used in variational minimization procedures. 
Such networks typically consist of two parts, one a set of complex tensors `A,B,C, ...` and the other a set of the complex conjugate of the first set, `conj(A), conj(B), ...`. Currently, building such networks with TensorNetwork is done by adding `A,B,C,...` and e.g. `tf.conj(A), tf.conj(B), ...` (for the tensorflow backend) into the network. As far as I know, the supported backends will create a copy of `A` upon calling the `conj` method on it. This uses twice as much memory as would be necessary if the `conj` method would be called on the fly when contracting the tensors, which can become a bottleneck for large networks and/or large bond dimensions. It would be nice to have a way of telling `TensorNetwork` if an added node should be conjugated prior to contraction, or to have an optional argument to `contract` which determines if tensors should be conjugated prior to contraction.

**Comment by amilsted** [comment]
At least with the TF backend, I don't think it matters whether `conj()` is called just before the contraction, or a lot before, if within a single computational graph - the memory for the copy will be allocated just the same. If `tensordot()` had conjugate flags, we could pass them on to `matmul()`, but IIRC `matmul()` just calls `conj()` on the input if you set the flag, rather than calling a conjugate version of GEMM... It's a bit sad.

**Comment by Thenerdstation** [comment]
JAX uses XLA by design and TF is going to switch to XLA very soon, so I think these optimizations will likely happen at compile time.
