### ISSUE TITLE
Our opt_einsum paths are not actually determanistic

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#228]
The contractors in `opt_einsum` do not actually give out deterministic results as we are using the edge object as the axis labels. This causes similar runs to have wildly different performance when using `greedy` and `branch`

**Comment by stavros11** [comment]
Why is it a problem that we label axis using the edge objects? After playing a bit, I think the reason the paths are not deterministic is `nodes = sorted(net.nodes_set)` which does not guarantee that the ordering of `nodes` and `input_sets` is the same when you re-initialize a network and call the contractor.

I have been able to reproduce the issue with a chain of matrix multiplications (with different dimensions) and `branch(nbranch=2)`. Substituting `sorted` with a hard-coded sorting solved the problem, however I am not sure if my example is a particular edge case.

Small note 1: the typing in [line 25](https://github.com/google/TensorNetwork/blob/ba54e2e29f6fbdc2d54b409fb30bb98fdec61072/tensornetwork/contractors/opt_einsum_paths/path_contractors.py#L25) is wrong: should be `List[Set[Edge]]`, etc.
Small note 2: Would it be a good idea to have contractor tests that actually check the paths? Because currently we only check the contraction result which would work even if we just contract naively. This may require to split the `base` method of `path_contractors.py`, because currently `path` is a local variable and probably not accessible by tests.

**Comment by Thenerdstation** [comment]
We should write tests to ensure the contraction order is deterministic. It would likely require a slight refector and use of mocked objects so it might be a little more work. Also, tests against things being deterministic are inherently flaky, so I'm not sure the best way to go forward.

**Comment by MichaelMarien** [comment]
So we want `nodes = sorted(net.nodes_set, key = lambda x: x.name)` and this would solve it?

Regarding the tests, if you can't easily test something, usually that means the design of the code can be optimised, so I'm all in favour of a slight refactor. As we are relying on opt_einsum anyway, perhaps we can get some inspiration from their tests: https://github.com/dgasmith/opt_einsum/blob/master/opt_einsum/tests/test_paths.py and redo them in tensornetwork language?

**Comment by stavros11** [comment]
I think adding the `key` would solve the non-deterministic issue, at least assuming standard use (one could still break it by randomizing node names). By standard use I mean constructing the `TensorNetwork` with a specific procedure, so node names (unlike node objects) should be the same in every construction. That being said, I cannot think of any other reason that paths are non-deterministic as this sorting seems to be the only source of "randomness". Edges (axis) are passed as unordered sets in `opt_einsum` anyway, that's why I don't think this causes any problem.

I could easily check paths by splitting the `path_contractors.base` method to two, one that calculates the `path: List[Tuple[int]]` and one that performs the contraction. This refactoring makes sense to me because the first part is pure `opt_einsum` while the second is pure `tensornetwork`. Then we could easily redo the `assert_contract_order` tests from `opt_einsum`, perhaps almost as they are.

**Comment by MichaelMarien** [comment]
Sounds great!

**Comment by Thenerdstation** [comment]
Sounds good to me too.

One change I would do is to use `node.signature` instead of `node.name` as `node.signature` has a better chance of being unique in the network.
