### ISSUE TITLE
jax backend is very slow for MPS

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#248]
I'm benchmarking the orthogonalization of an MPS, and the JAX backend is
**much** slower than numpy, tensorflow and torch. Here is the code I'm running (you can't run this yet because the PR hasn't been merged yet).
```python 
import tensornetwork as tn
import numpy as np
import time
import tensorflow as tf

tf.enable_v2_behavior()
%load_ext autoreload
%autoreload 2
import torch
D, d, N = 50, 2, 100
backend='numpy' #'jax','tensorflow','pytorch'
tensors = [np.random.rand(1,d,D)] + [np.random.rand(D,d,D) for _ in range(N-2)] + [np.random.rand(D,d,1)]
mps = tn.mps.FiniteMPS(tensors, center_position=0, backend=backend)
times = []
for n in range(10):
    print(n)
    t1 = time.time()
    mps.position(N-1)
    times.append(time.time() - t1)
    t1 = time.time()
    mps.position(0)
    times.append(time.time() - t1)
print(np.average(times))
```
with these results

numpy: 0.05262857675552368
tensorflow: 0.26129311323165894
jax: 19.893924355506897
torch: 0.07801413536071777

We know that to get numpy like performance with tensorflow on CPU we need to wrap 
contractions into @tf.function. In the experiments/MPS stuff, we used defuned ncon calls to get a speed with tensorflow similar to numpy on CPU. Similarly, we should use jax.jit for the jax backend. 

We could try to wrap functions in the TensorNetwork.backend (like e.g. tensordot2
and matrix decompositions). The other option is to introduce new backends for the MPS library which use `tf.function` or `jax.jit` to get good performance.

**Comment by Thenerdstation** [comment]
I'd rather not wrap everything with a jit as it can cause really nasty performance issue when shapes are missatched and everything is getting recompiled.

Though this sounds more like a bug in JAX. We should bring it up on their end.

**Comment by mganahl** [comment]
OK, I'll  investigate a bit more to track down the problem. 
We should though think of ways of making also tensorflow in eager mode as fast as numpy for small bond dimensions (where the overhead of graph building is most severe). The other alternative is to have a new backend object in the MPS which handles this kind of stuff

**Comment by Thenerdstation** [comment]
Since we are switching to JAX being the default, I don't think it's in our best interest to try to work on TF benchmarks (with the exception of complete failures).

I also don't think it's worth our time to be worrying about benchmarks for really small scale experiments at low bond dimension, especially on CPU. No one really cares about the difference between 0.05 seconds and 0.26 seconds unless they are doing things repeatedly (in which case, they would just use `jax.jit` and the problem would go away) Users care more about usability, not unnoticeable micro benchmarks.

**Comment by amilsted** [comment]
> I also don't think it's worth our time to be worrying about benchmarks for really small scale experiments at low bond dimension, especially on CPU. No one really cares about the difference between 0.05 seconds and 0.26 seconds unless they are doing things repeatedly (in which case, they would just use `jax.jit` and the problem would go away) Users care more about usability, not unnoticeable micro benchmarks.

Does "jitting" of very high-level functions currently work with JAX? Also, with TF there is an important compile time vs. execution time trade-off in choosing at what level to "compile" functions. This led us to put some mid-level "defunning" into the experimental MPS code, because doing defun on the high-level stuff was just too slow. To what extent is this true for JAX? Can the user JIT the high-level stuff without incurring excessive compile times?

**Comment by Thenerdstation** [comment]
The issue might be related to this, https://github.com/google/jax/issues/1344

**Comment by Thenerdstation** [comment]
Hmm. So I've been thinking about this and I think I might know the issue.

So in JAX, we convert numpy arrays to jax's numpy arrays via a `jax.jit` call on an identity function (see https://github.com/google/TensorNetwork/blob/f62cc5269dfc09662ae9ced7325ba8787b0a2c27/tensornetwork/backends/jax/jax_backend.py#L38).

I have a bad feeling this is the issue.

**Comment by Thenerdstation** [comment]
Is this still the case?

**Comment by Thenerdstation** [comment]
Post `jit`s this isn't the case anymore right?

**Comment by mganahl** [comment]
yes, that's actually also fixed :)
