### ISSUE TITLE
Add machine learning examples

### ISSUE THREAD

**Issue by MagicTK** [google/TensorNetwork#308]
I couldn't find the experiment for paper 'TensorNetwork for Machine Learning' (arXiv:1906.06329). I hope you might consider adding some examples of machine learning, and it’s best to provide the code in the README paper experiment (MNIST or Fashion-MNIST). Thank you!

**Comment by Thenerdstation** [comment]
You can view the code from the commit just before we removed it.

https://github.com/google/TensorNetwork/tree/113015b9ff034d38432e30a663f048067f25c6de

Keep in mind, all of the code in `experiments` never went through code review and isn't up to Google standards (which is why we deleted it). We were going through large API changes this last week and decided keeping this code working wasn't worth the trouble.

**Comment by mganahl** [comment]
Hi @MagicTK, I kept a backup of the repo on the branch `master_experiments` on my fork of the repo. You can clone it if you need the code. Note however that this branch will __not__ be kept up-to-date with the upstream master branch.

**Comment by meigel** [comment]
I am also interested in this paper and the respective code example. Would be great if you could provide a proper implementation after the refactoring!

**Comment by MagicTK** [comment]
Thanks ever so :)
