### ISSUE TITLE
Should 3sat be in examples rather than experiments?

### ISSUE THREAD

**Issue by amilsted** [google/TensorNetwork#37]
We made a distinction in order to separate complicated code from relatively simple examples.

For example: The wavefunctions code is quite short and also directly uses the TN API rather than the ncon interface. The MPS, MERA, and Tree code is quite long and mostly uses ncon.

I feel like 3sat is short enough to go in examples. It also does not use ncon, making it a good example of how to use the API directly.

**Comment by amilsted** [comment]
Then again, it doesn't currently have a script component that runs an instance. Could it acquire one? :)

**Comment by Thenerdstation** [comment]
I guess the bigger question is what extensions should exist between experiments/examples? Should there even be a difference?

**Comment by amilsted** [comment]
That is a bigger question. It seemed sensible to distinguish when @mganahl and I were discussing this with @sleichen, since there is a big difference in code complexity. However, I suppose we could just add READMEs for each one explaining what it is and indicating its complexity (or suitability as a pedagogical example for beginners).

**Comment by Thenerdstation** [comment]
Hmm. How about we merge them into one folder call `extensions` since they basically all extend TensorNetwork functionality.

**Comment by mganahl** [comment]
I think `examples` should contain a collection of code highlighting basic use cases of the API, without too much additional stuff happening around it, so that users can get started quickly with the basic things. The `experiments` folder for now contains relatively heavy weight numerics, and I don't think most of the stuff there is of any use for someone who just wants to see the API in action. So as long as we don't have a more extensive documentation, I'd put stuff which uses the API directly, and isn't too complicated to understand, in the `examples` folder.

**Comment by Thenerdstation** [comment]
Yeah that seems reasonable to me. 

Ok cool, `examples` will be for teaching and `experiments` will be for complicated stuff that we might make part of the library in the future. SGTM.

Now, should 3SAT be an `example` or an `experiment`?

**Comment by mganahl** [comment]
I'd put it in `examples`. It's not too complicated, and its a good example of how to use the API

**Comment by amilsted** [comment]
At the moment I agree. We can still decide to make it a part of the API later, if we want.

**Comment by Thenerdstation** [comment]
Cool. Anyone wanna make a PR? :smile:

**Comment by Thenerdstation** [comment]
https://github.com/google/TensorNetwork/pull/49
