### ISSUE TITLE
axis_names differ from Edge.name after contraction

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#38]
Currently, when building a network and giving names to all node-axis and all contraction edges, the resulting node after calling `net.contract(e)` for all Edges `e` has default `axis_names`, while the Edges of the node are correctly labeled by the original labels. 
```
D=4
A = np.random.rand(D,D,D,D)
B = np.random.rand(D,D,D,D)
net = tn.TensorNetwork()
n1 = net.add_node(A,axis_names=['A1', 'A2', 'A3', 'A4'])
n2 = net.add_node(B,axis_names=['B1', 'B2', 'B3', 'B4'])
e1 = net.connect(n1[0], n2[0],name='e1')
e2 = net.connect(n1[2], n2[3],name='e2')
net.contract(e1)
out = net.contract(e2)

print(out.axis_names) #prints ['__Edge_8', '__Edge_9', '__Edge_10', '__Edge_11']
print([e.name for e in out.get_all_edges()]) #prints ['A2', 'A4', 'B2', 'B3']
```
Same for `contract_between`

**Comment by amilsted** [comment]
We had some discussion on a related matter in the previous repo. Since axis names are not required to be globally unique, there are cases when they cannot be preserved after contraction (e.g. if n1 and n2 have axes with the same names that are not contracted). Are edge names globally unique? I forget...

Anyway, I guess one could take a best-effort approach and maintain axis names where they don't conflict. One could append node names to the new axis names in case of conflict (e.g. ['A4_n1', 'A4_n2']). This might be a little too obscure to be relied upon, however.

**Comment by Thenerdstation** [comment]
No names are globally unique, mainly because they don't have to be. 

Preserving names post contraction is gonna be very messy and there isn't really a good solution. They either have to

1. Be unique, which can cause frustrating errors when extending networks or when you want to reuse a name like `net.connect(a['alpha'], b['alpha'])`
2. Have names append some string, which is honestly even worse because now you might have no idea what string you actually should be using.
3. Don't preserve names after contraction and tell users to just use the edge objects.

I think that 3 is by far the cleanest and that is what we have. If you can think of a 4th option please lmk.

**Comment by amilsted** [comment]
Yeah, I agree. I think 3 is the least bad option.

For keeping track of output edges, I've just been grabbing edge objects early on and keeping them around to refer to later. Since edges that are not themselves contracted persist across contractions, one can continue to use them for `reorder_edges()` or for connecting new nodes later.

**Comment by amilsted** [comment]
Just throwing this out there (probably garbage): We could alternatively make it an error to have axis names that conflict  *on contraction*. This does not imply global uniqueness.

**Comment by Thenerdstation** [comment]
That feels scary to me. What if the collision happens near the end and break because of a generated network. How could you figure out what line you need to change?

**Comment by amilsted** [comment]
Yeah, it does seem like a recipe for obscure errors...
Also I can think of cases where I definitely wouldn't want it, e.g. blocking two tensors in a matrix product state with axes `['L','p','R']` and `['L','p','R']` by connecting 'R' with 'L'. This is a totally reasonable thing to do but results in a 'p' conflict.

**Comment by Thenerdstation** [comment]
Closing as WAI
