### ISSUE TITLE
Support for reshaping tensors

### ISSUE THREAD

**Issue by rdilip** [google/TensorNetwork#483]
I'm wondering what the preferred method of reshaping a tensor is? The method I've been using thus far has been 
```python
# a is some node with shape (2,2,2)
a = tn.Node(a.tensor.reshape((4,2)))
```
It seems like there should be a way already built-in, but I have not been able to find anything in the documentation.

**Comment by Thenerdstation** [comment]
What's your goal?

**Comment by rdilip** [comment]
I have a generic method that acts on MPOs, where each MPO is represented as a list of L rank 4 nodes. From a different method, I've constructed an MPO where the bottom-most tensor is rank 3, and I wanted to reshape that with a trivial leg to feed it back into my method that acts on MPOs. Of course, I could just catch this particular case in my first method or take an outer product with a trivial vector, so my question is less motivated by this particular goal, and more by wanting to learn how to use the library properly Is the philosophy to just provide the methods that generally make reshaping necessary (e.g., split_nodes_qr)?

**Comment by Thenerdstation** [comment]
Aw I see. For now your method would work but it would be nice to add some sort of reshaping feature.

We have an issue open for #150 which would get you close to what you want. Full reshapes however could get messy once nodes are connected to each other so I'm not sure we will support that (especially since your method works well enough).

**Comment by rdilip** [comment]
Thanks!
