### ISSUE TITLE
rename svd_decomposition to sv_decomposition

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#582]
I feel we should rename `svd_decomposition` to `sv_decomposition` since the former
has a redundant "decomposition" in it.

**Comment by alewis** [comment]
Is there a problem with `svd`?

**Comment by mganahl** [comment]
find with me too

**Comment by Thenerdstation** [comment]
I vote `truncatable_svd`

**Comment by alewis** [comment]
It is true that the built in ability to truncate does mean we depart somewhat from what numpy does, but per the v1.0 push to make the syntax NumPy like where possible and since tensor network SVDs are almost always truncated, it would strike me that simply `svd` is more natural, unless we plan to reserve that name for something else (which would seem strange to me).
