### ISSUE TITLE
ncon is not as fast as it could be

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#650]
I rewrote `ncon` to use directly the backend methods `tensordot`, `transpose`, `reshape` and some others, and it turns out that it is much faster than our current `tn.ncon`
```python 
D = 800
D1=12
D2 = 10
a = np.random.rand(D1,D,D)
b = np.random.rand(D,D,D2)

print(timeit.timeit(lambda: tn.ncon([a,b],[[-1,1,2,],[1,2,-2]],backend='numpy'), number=100)) #takes ~ 3 seconds
print(timeit.timeit(lambda: ncon([a,b],[[-1,1,2,],[1,2,-2]],backend='numpy'), number=100)) #takes ~ 1 second
```

**Comment by Thenerdstation** [comment]
Nice! I'm curious why that is the case. Is it the python overhead or is it better contraction methods?

**Comment by mganahl** [comment]
Not sure. I'm using tensordot to contract tensors, and I'm doing nothing fancy. The difference seems to depend on the order of the contracted indices.

**Comment by gevenbly** [comment]
Hey guys, for comparison I tested the `tn.ncon` with numpy backend against my own version of numpy `ncon` and found similar results to Martin (with the `tn.ncon` taking 4-5 times longer for the example considered above). I also tested my MATLAB version of `ncon` and found it to have identical performance to my numpy version in this example (which is not surprising since the tensors in the example are large enough such that almost all of the computation time is spent in matrix-matrix multiplication, so the difference in the language-specific overheads is negligible). 

I also tried a different example (that now requires tensor permutations):
```
D1 = 12
D2 = 10
a = np.random.rand(D,D,D1)
b = np.random.rand(D2,D,D)

print(timeit.timeit(lambda: ncon([a,b],[[1,2,-1],[-2,1,2]]), number=100)) 
print(timeit.timeit(lambda: tn.ncon([a,b],[[1,2,-1],[-2,1,2]],backend='numpy'), number=100)) 
```
In this example the `tn.ncon` was 12-15 times slower than my numpy `ncon`, so it seems there is a significant efficiency issue for existing numpy backend for `tn.ncon`.

**Comment by Thenerdstation** [comment]
That's really strange, especially since all ncon should be doing is calling tensordot...

**Comment by Thenerdstation** [comment]
In Glen's code, the tensors are also really small and there's only 1 multiplication happening. I think it's likely just a ton of python overhead.

**Comment by gevenbly** [comment]
Whoops, I forgot to specify but I set `D = 800` in my example (so the tensor dimensions are the same as in Martins example, the only difference is a permutation is involved). So these are a 800-by-800-by-12 tensor and a 10-by-800-by-800 tensor, which are large enough such that the relative overhead is minimal.

**Comment by mganahl** [comment]
I noticed that the variance of the runtime of `tn.ncon` is really high. Some runs are as fast as a simple `ncon` call, but about half of them are really slow.

**Comment by mganahl** [comment]
This happens actually for all other backends as well, with the expection of the tensorflow backend (I didn't test symmetric backend).

**Comment by mganahl** [comment]
The high variance seems to suggest that it could be related to python overhead, in which case though we should definitely switch to the other version.

**Comment by Thenerdstation** [comment]
No arguments on my end.

**Comment by mganahl** [comment]
I'll prepare a PR. It will still be worth finding out what's causing this. If it's some python overhead in the Node or Edge classes we might want to fix it.

**Comment by mganahl** [comment]
@Thenerdstation congrats btw on you last paper! looks very nice!

**Comment by Thenerdstation** [comment]
Thanks haha. Jensen did basically all of the work, but I had the idea 😎.

**Comment by refraction-ray** [comment]
I think I have found some hints on this issue.
```python
D = 800
D1=12
D2 = 10
a = np.random.rand(D1,D,D)
b = np.random.rand(D,D,D2)

print(timeit.timeit(lambda: np.tensordot(a,b, [[1,2], [0,1]]), number=100)) #takes ~ 2.7 seconds
print(timeit.timeit(lambda: np.tensordot(a,b, [[2,1], [1,0]]), number=100)) #takes ~ 8.5 seconds
```
and of course they are the same
```python
np.allclose(np.tensordot(a,b, [[1,2], [0,1]]),np.tensordot(a,b, [[2,1], [1,0]]) ) # True
```

somehow TN utilize the slow axes arguments in tensordot. But this in general is not an issue from TensorNetwork or python overhead here. It is just weird to see the performance difference in ``numpy.tensordot`` with barely the same thing. I guess the possible reason is in the slower case, a transpose is explicitly invoked.

**Comment by refraction-ray** [comment]
And for the high variance part, 
```python
tn.ncon([a,b],[[-1,1,2],[1,2,-2]])
```
this thing actually gives the tensordot axes as ``[[1,2], [0,1]]`` and ``[[2,1], [1,0]]`` stochastically... for each run, the tensordot axes can be different.

**Comment by Thenerdstation** [comment]
Aw, that makes a ton of sense.

Do we know what order is consistently faster? We could probably add an optimization of it in `contract_between`.

**Comment by refraction-ray** [comment]
> Do we know what order is consistently faster?

I am not an expert on this so I am not very sure. But I find this problem persists in opt_einsum and numpy with einsum str instead of ncon interface.

```python
D = 800
D1 = 12
D2 = 10
a = np.random.rand(D1,D,D)
b = np.random.rand(D,D,D2)
print(timeit.timeit(lambda: np.einsum("ijk, jkl->il", a, b, optimize=True), number=100)) # 2.5s
print(timeit.timeit(lambda: np.einsum("ikj, kjl->il", a, b, optimize=True), number=100)) # 19s
print(timeit.timeit(lambda: oe.contract("ijk, jkl->il", a, b), number=100)) # 19s
print(timeit.timeit(lambda: oe.contract("ikj, kjl->il", a, b), number=100)) # 2.5s
```

I will open an issue in opt_einsum, the authors there are experts on this.

**Comment by gevenbly** [comment]
Okay, so its seems that the performance difference between the ncon's here relates to how much tensor permutation is done. Hey @mganahl, this lend itself to an easy way to improve the new numpy version of ncon.  If we consider the examples discussed previously:

```
D = 800
D1=12
D2 = 10
a = np.random.rand(D1,D,D)
b = np.random.rand(D,D,D2)

print(timeit.timeit(lambda: ncon([a,b],[[-1,1,2,],[1,2,-2]]), number=100)) 
print(timeit.timeit(lambda: ncon([a,b],[[-1,2,1,],[2,1,-2]]), number=100)) 
```

then I find the second line takes ncon several times longer than the first, even though they represent the same contraction. However if I put just a few extra lines into ncon (right before the `tensordot` call):

```
ind_order = np.argsort(A_cont)
A_cont = A_cont[ind_order]
B_cont = B_cont[ind_order]
```

then the problem is fixed, and both of the examples evaluate quickly. These lines ensure that tensordot is called with `axes = [[1,2], [0,1]]` in both instances, rather than axes = `[[2,1], [1,0]]` in the second instance. In general, I think it would always be a good idea to have the contracted indices follow the order that the indices appear on one of the tensors (i.e. so that at least one of the lists in `axes` is in ascending order when presented to tensordot). It may also be worthwhile to experiment to find some heuristics along these lines. For instance, I think it would be better to take the axes order for `tensordot` from the tensor with largest `size`, such that the permutation is limited to the smaller of the tensors where-ever possible. It may also be advantageous to switch the input order of the tensors given to `tensordot` in some circumstances.

**Comment by gevenbly** [comment]
In a practical calculation (contracting a binary MERA) changing the ncon to ensure that for each call to `tensordot` that one of the `axes` is always in ascending order, as described above, results in about a 10% speedup. This seems definitely worthwhile to do!

**Comment by Thenerdstation** [comment]
yeah, seems pretty easy also. We'd need to change this section to account for the better order.

https://github.com/google/TensorNetwork/blob/72360d6b0ec91b2b5b7e0c04fcc1641908def50b/tensornetwork/network_components.py#L1983

@gevenbly, do you wanna give it a try? It could be a nice first PR to the library. :)

**Comment by Thenerdstation** [comment]
@refraction-ray you're also welcome to give it a crack.

**Comment by gevenbly** [comment]
@Thenerdstation, I think that Martin is already preparing a PR for the ncon, so we should wait for this. As far as I understand, ensuring this could be just a 1-line fix to ensure that tensordot always has a sequential order for axes, i.e. if we replace:
```
backend.tensordot(node1.tensor, node2.tensor, [axes1, axes2])
```
with instead:
```
ind_order = argsort(axes1)
backend.tensordot(node1.tensor, node2.tensor, [axes1[ind_order], axes2[ind_order]])
```
then it should do the trick.
